// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsydNCNODCYOtO7YuMVTNbijS13x_r5b0',
    appId: '1:765369289723:web:6762ebab82618fade6d95e',
    messagingSenderId: '765369289723',
    projectId: 'flutter-chat-app-155e1',
    authDomain: 'flutter-chat-app-155e1.firebaseapp.com',
    storageBucket: 'flutter-chat-app-155e1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvoum8UTX9eCtfyb2DcXYC-POEjI68aik',
    appId: '1:765369289723:android:e1f0cf25869c2d0ae6d95e',
    messagingSenderId: '765369289723',
    projectId: 'flutter-chat-app-155e1',
    storageBucket: 'flutter-chat-app-155e1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYDjpaDhpV6Euf9XWDvTO3PO5WprLYsG8',
    appId: '1:765369289723:ios:38180130c65f75a1e6d95e',
    messagingSenderId: '765369289723',
    projectId: 'flutter-chat-app-155e1',
    storageBucket: 'flutter-chat-app-155e1.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYDjpaDhpV6Euf9XWDvTO3PO5WprLYsG8',
    appId: '1:765369289723:ios:38180130c65f75a1e6d95e',
    messagingSenderId: '765369289723',
    projectId: 'flutter-chat-app-155e1',
    storageBucket: 'flutter-chat-app-155e1.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAsydNCNODCYOtO7YuMVTNbijS13x_r5b0',
    appId: '1:765369289723:web:64914ee95e5e86bbe6d95e',
    messagingSenderId: '765369289723',
    projectId: 'flutter-chat-app-155e1',
    authDomain: 'flutter-chat-app-155e1.firebaseapp.com',
    storageBucket: 'flutter-chat-app-155e1.firebasestorage.app',
  );

}